import Head from "next/head";
import { useState, useEffect, useContext } from "react";
import { ArtworkContext } from "@/providers/ArtworkProvider";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";

import ArtworkMap from "@/components/ArtworkMap";
import ArtworkList from "@/components/ArtworkList";
import Logo from "@/components/Logo";
import Nav from "@/components/Nav";
import Loader from "../components/Loader";

const IndexPage = () => {
  const [artwork, setArtwork] = useContext(ArtworkContext);
  const { t } = useTranslation("common");
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    if (artwork.original.length !== 0) {
      setIsLoading(false);
    }
  }, [artwork.original]);

  return (
    <>
      <Head>
        <title>A Colorful History</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="index-container">
        {!isLoading && <Logo />}
        {!isLoading && <Nav />}
        {isLoading ? (
          <Loader />
        ) : artwork.viewMap ? (
          <ArtworkMap />
        ) : (
          <ArtworkList />
        )}
      </main>
    </>
  );
};

export default IndexPage;

export async function getStaticProps({ locale = "en" }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common"])),
    },
  };
}
